jobs:
  build:
    runs-on: windows-2025
    steps:
      # Check-out repository
      - uses: actions/checkout@v4
      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      # Build an executable from your Python code (standalone *.exe or *.bin file executables and even .app bundles for Mac)
      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: qtsvg.py
          mode: standalone
          enable-plugins: pyside6
      # Uploads artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: build/qtsvg.exe
          include-hidden-files: true